name: probe
on:
  push:
permissions:
  contents: read
jobs:
  call:
    uses: seolith-llc/seolith-dev-standards/.github/workflows/secret-scan.yml@c5ea98da5a549771aaba1e15fc3c6eb4a2dd8904 # main
    with:
      runs-on: '["self-hosted","Linux","X64","seolith-local","linux-build"]'
