name: probe
on:
  push:
permissions:
  contents: read
jobs:
  call:
    uses: seolith-llc/seolith-dev-standards/.github/workflows/secret-scan.yml@2b6fad978ae3f98e824cd2210438b03a503c1444 # v1.1.4
    with:
      runs-on: '["self-hosted","Linux","X64","seolith-local","linux-build"]'
